VERSION 0.7

ARG --global DATE=(date +%y-%m-%d)
ARG --global DEBIAN_VERSION=bullseye-20230109-slim
ARG --global ELIXIR_VERSION=1.14.5
ARG --global OTP_VERSION=25.2.1
ARG --global NODE_MAJOR=18

image:
    FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}
    WORKDIR /app
    RUN apt-get update
    RUN apt-get install -y ca-certificates curl gnupg git build-essential
    RUN mkdir -p /etc/apt/keyrings
    RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    RUN apt-get update
    RUN apt-get install nodejs -y
    RUN mix local.hex --force && mix local.rebar --force

deps:
    FROM +image
    COPY mix.exs .
    COPY mix.lock .
    RUN mix deps.get

test:
    FROM +deps
    ENV MIX_ENV=test
    COPY . .
    WITH DOCKER --allow-privileged --pull ankane/pgvector 
        RUN mix testd
    END

build:
    FROM +deps
    ENV MIX_ENV=prod
    COPY config/config.exs config/${MIX_ENV}.exs config/
    RUN mix deps.compile
    COPY priv priv
    COPY lib ./lib
    COPY assets assets
    RUN mix assets.deploy
    RUN mix compile
    COPY config/runtime.exs config/
    COPY rel rel
    RUN mix release
    SAVE ARTIFACT _build/prod AS LOCAL _build/prod

docker:
    FROM debian:${DEBIAN_VERSION}
    WORKDIR /app
    RUN apt-get update -y && apt-get install -y libstdc++6 openssl libncurses5 locales \
        && apt-get clean && rm -f /var/lib/apt/lists/*_*
    RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US:en
    ENV LC_ALL en_US.UTF-8
    ENV MIX_ENV="prod"
    COPY +build/app/_build/${MIX_ENV}/rel/akashi ./
    USER nobody
    CMD ["/app/bin/server"]
    SAVE IMAGE akashi:latest
    SAVE IMAGE --push registry.fly.io/akashi:latest registry.fly.io/akashi:${DATE}

deploy:
    RUN fly deploy --image registry.fly.io/akashi:latest

libs:
    LOCALLY
    RUN cp -r ../libs/ipfs_pinning_service_api .
