image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      mise install

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - alefragnani.project-manager
    - amazonwebservices.aws-toolkit-vscode
    - arrterian.nix-env-selector
    - ayushh.vscode-anchor
    - bradlc.vscode-tailwindcss
    - charliermarsh.ruff
    - christian-kohler.path-intellisense
    - codeium.codeium
    - codezombiech.gitignore
    - continue.continue
    - doppler.doppler-vscode
    - eamodio.gitlens
    - eamodio.tsl-problem-matcher
    - elixir-lsp.elixir-ls
    - erlang-ls.erlang-ls
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - franneck94.c-cpp-runner
    - fwcd.kotlin
    - genuitecllc.codetogether
    - github.vscode-pull-request-github
    - golang.go
    - hashicorp.terraform
    - jeanp413.open-remote-ssh
    - jnoortheen.nix-ide
    - julialang.language-julia
    - mads-hartmann.bash-ide-vscode
    - mikestead.dotenv
    - mkhl.direnv
    - ms-azuretools.vscode-docker
    - ms-python.debugpy
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-vscode.makefile-tools
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - mtxr.sqltools-driver-sqlite
    - nomicfoundation.hardhat-solidity
    - pomdtr.excalidraw-editor
    - prisma.prisma
    - quarto.quarto
    - redhat.ansible
    - redhat.java
    - redhat.vscode-yaml
    - rust-lang.rust-analyzer
    - samuelcolvin.jinjahtml
    - scala-lang.scala
    - scalameta.metals
    - sumneko.lua
    - tailscale.vscode-tailscale
    - tamasfe.even-better-toml
    - teabyii.ayu
    - tobermory.es6-string-html
    - tomoki1207.pdf
    - unifiedjs.vscode-mdx
    - vadimcn.vscode-lldb
    - victorbjorklund.phoenix
    - vmware.vscode-spring-boot
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - vue.volar
    - xaver.clang-format
    - xyz.local-history
