image:
  # gitpod/workspace-full
  file: .gitpod.Dockerfile

tasks:
  - init: |
      mise install

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - erlang-ls.erlang-ls
    - elixir-lsp.elixir-ls
    - ms-python.python
    - rust-lang.rust-analyzer
    - franneck94.c-cpp-runner
    - mads-hartmann.bash-ide-vscode
    - mkhl.direnv
    - tamasfe.even-better-toml
    - redhat.vscode-yaml
