# fly.toml file generated for mvkvc-protohackers on 2023-05-03T14:12:44-04:00

app = "mvkvc-protohackers"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "yyz"
processes = []

[build]

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.port]]
    handlers = []
    port = "5001"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
