[tool.poetry]
name = "site"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
mkdocs-material = "^9.5.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
