# fly.toml app configuration file generated for critique on 2023-06-27T17:27:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "critique"
primary_region = "yyz"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "critique.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
