VERSION 0.7

ARG --global DATE=(date +%y-%m-%d)
ARG --global DEBIAN_VERSION=slim-bullseye
ARG --global PYTHON_VERSION=3.10
ARG --global NODE_MAJOR=18

image:
    FROM python:${PYTHON_VERSION}-${DEBIAN_VERSION}
    WORKDIR /app
    RUN apt-get update
    RUN apt-get install -y ca-certificates curl gnupg git build-essential
    RUN mkdir -p /etc/apt/keyrings
    RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    RUN apt-get update
    RUN apt-get install nodejs -y
    RUN python3 -m pip install --user pipx
    ENV PATH="/root/.local/bin:$PATH"
    RUN python3 -m pipx ensurepath
    RUN pipx install poetry

deps:
    FROM +image
    COPY contracts/ tests/ ape-config.yaml hardhat.config.ts package-lock.json package.json poetry.lock pyproject.toml tsconfig.json .
    RUN npm i -D
    RUN poetry install --no-root

test:
    FROM +deps
    RUN poetry run pytest
    RUN npm run test

build:
    FROM +deps
    RUN poetry run ape compile ./contracts/*.vy 
    SAVE ARTIFACT .build AS LOCAL .build

libs:
    LOCALLY
    RUN cp -r ../libs/snekmate ./contracts
