# fly.toml app configuration file generated for mina-btc-oracle-server on 2024-03-04T16:36:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mina-btc-oracle-server'
primary_region = 'yyz'

[build]

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
