VERSION 0.7

test:
    BUILD ./app+test
    BUILD ./contracts+test

build:
    BUILD ./app+build
    BUILD ./contracts+build

docker:
    BUILD ./app+docker

# deploy:
#     BUILD ./app+deploy
#     BUILD ./site+deploy

libs:
    BUILD ./app+libs
    BUILD ./contracts+libs
    