[package]
name = "tissue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
relative-path = "1.9.2"
webbrowser = "1.0.1"
