defaults:
- base
price_levels: 10
col_prices_ask_re: (?=.*price)(?=.*ask)
col_prices_bid_re: (?=.*price)(?=.*bid)
col_volumes_ask_re: (?=.*amount)(?=.*ask)
col_volumes_bid_re: (?=.*amount)(?=.*bid)
col_sort: \d+
path: ../data/test/parquet/book_snapshot_25/ETHUSDT
_target_: rlmm.datasets.DatasetBook
