# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_chunk.ipynb.

# %% auto 0
__all__ = ['ChunkFn', 'ChunkStrategy', 'chunk_supported']

# %% ../nbs/03_chunk.ipynb 4
ChunkFn = ...
ChunkStrategy = ...

# %% ../nbs/03_chunk.ipynb 5
chunk_supported = {
    #
}
