# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_rerank.ipynb.

# %% auto 0
__all__ = ['RerankResult', 'RerankFn', 'Client', 'RerankModel', 'RerankRequest']

# %% ../nbs/06_rerank.ipynb 4
from functools import partial
from typing import Any, Awaitable, Callable, List, Union

import numpy as np
from pydantic import BaseModel, Field

# %% ../nbs/06_rerank.ipynb 5
RerankResult = List[Union[float, np.array]]
RerankFn = Callable[[str], Union[Awaitable[RerankResult], RerankResult]]
Client = Any

# %% ../nbs/06_rerank.ipynb 6
class RerankModel(BaseModel):
    async_: bool
    init_key: Union[str, None]
    max_query_tokens: int
    max_doc_tokens: int
    max_docs: int
    fn_init: Callable[[Union[str, None]], Client]
    fn_rerank: Callable[[Client], RerankFn]
    max_batch: int = Field(default=1)

# %% ../nbs/06_rerank.ipynb 7
class RerankModel(BaseModel):
    async_: bool
    init_key: Union[str, None]
    max_query_tokens: int
    max_doc_tokens: int
    max_docs: int
    fn_init: Callable[[Union[str, None]], Client]
    fn_rerank: Callable[[Client], RerankFn]
    max_batch: int = Field(default=1)

# %% ../nbs/06_rerank.ipynb 8
class RerankRequest(BaseModel):
    query: str
    docs: List[str]
    model_str: str = Field(default="cohere_rerank-english-v3.0")
