# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tokens.ipynb.

# %% auto 0
__all__ = ['TIKTOKEN_ENCODINGS', 'count_tokens']

# %% ../nbs/02_tokens.ipynb 3
import tiktoken

# %% ../nbs/02_tokens.ipynb 4
TIKTOKEN_ENCODINGS = ["cl100k_base"]

# %% ../nbs/02_tokens.ipynb 5
def count_tokens(text: str, encoding_str: str = "cl100k_base") -> int:
    if encoding_str in TIKTOKEN_ENCODINGS:
        encoding = tiktoken.get_encoding(encoding_str)
        num_tokens = len(encoding.encode(text))
    else:
        raise ValueError(f"Invalid encoding: {encoding_str}")

    return num_tokens
