# fly.toml app configuration file generated for mvkvc-walter on 2023-09-15T13:02:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mvkvc-walter"
primary_region = "yyz"

[build]

[[services]]
