name: apps_bountisol_app_deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/apps_bountisol_app_deploy.yml
  #     - apps/bountisol/app/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/bountisol/app
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
