name: apps_exboost_app_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/app_deploy.yaml
      - apps/exboost/app/**

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a exboost-app --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.TOKEN_FLY }}
        working-directory: apps/exboost/app
